proxy-providers:
  YZT:
    url: "https://sub.yztcloud.cc/getnodeinfo?token=63b704a74dedaf27ff61f0405196d75f"
    type: http
    exclude-filter: "每天"
    interval: 86400
    health-check:
      {
        enable: true,
        url: "https://www.gstatic.com/generate_204",
        interval: 300,
      }
    override:
      additional-prefix: "[YZT]"

  iKuuu:
    url: "https://f0dr3.no-mad-world.club/link/2ld7oTKIOFeVTrYa?clash=4&extend=1"
    type: http
    exclude-filter: "免费|测试"
    interval: 86400
    health-check:
      {
        enable: true,
        url: "https://www.gstatic.com/generate_204",
        interval: 300,
      }
    override:
      additional-prefix: "[iKuuu]"

mode: rule
ipv6: true
log-level: info
allow-lan: true
mixed-port: 7890
unified-delay: true
tcp-concurrent: true
geodata-mode: true
keep-alive-interval: 15
find-process-mode: strict
global-client-fingerprint: chrome
external-controller: 127.0.0.1:9090

profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ["rule-set:fakeip-filter,private,cn"]
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.google/dns-query

sniffer:
  enable: true
  parse-pure-ip: true
  sniff:
    {
      HTTP: { ports: [80, 8080-8880] },
      TLS: { ports: [443, 8443] },
      QUIC: { ports: [443, 8443] },
    }
  force-domain:
    - +.v2ex.com
    - google.com
  skip-domain: ["Mijia Cloud", "dlg.io.mi.com", "+.apple.com"]

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  device: mihomo
  strict-route: true

# proxies:

proxy-groups:
  - {
      name: Proxy,
      type: select,
      proxies:
        [
          Select,
          IEPL,
          Home,
          Direct,
          HongKong,
          TaiWan,
          Japan,
          Singapore,
          USA,
          DIRECT,
        ],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png,
    }
  - {
      name: Select,
      type: select,
      include-all-providers: true,
      icon: https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png,
    }
  - {
      name: IEPL,
      type: select,
      include-all-providers: true,
      filter: "(?i)IEPL",
      icon: https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/fallback.png,
    }
  - {
      name: Home,
      type: select,
      include-all-providers: true,
      filter: "(?i)家宽",
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Back.png,
    }
  - {
      name: Direct,
      type: select,
      include-all-providers: true,
      filter: "(?i)直连",
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png,
    }

  - {
      name: Final,
      type: select,
      proxies: [Proxy, DIRECT],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png,
    }

  - {
      name: AI,
      type: select,
      proxies: [USA, Home],
      icon: https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/openai.png,
    }
  - {
      name: CDN,
      type: select,
      proxies: [Download, DIRECT],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png,
    }
  - {
      name: Download,
      type: url-test,
      include-all-providers: true,
      filter: "(?i)下载|低倍率",
      lazy: true,
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Download.png,
    }
  - {
      name: Apple,
      type: select,
      proxies: [DIRECT, Proxy],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png,
    }
  - {
      name: Google,
      type: select,
      proxies: [Proxy, DIRECT],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png,
    }
  - {
      name: Microsoft,
      type: select,
      proxies: [DIRECT, Proxy],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png,
    }
  - {
      name: Samsung,
      type: select,
      proxies: [DIRECT, Proxy],
      icon: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Samsung_icon.svg/238px-Samsung_icon.svg.png,
    }
  - {
      name: Telegram,
      type: select,
      proxies: [Proxy, Select],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png,
    }
  - {
      name: Game,
      type: select,
      proxies: [DIRECT, Proxy],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png,
    }
  - {
      name: Streaming,
      type: select,
      proxies: [Proxy, DIRECT, HongKong, USA],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png,
    }
  - {
      name: Global,
      type: select,
      proxies: [Proxy, DIRECT],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png,
    }
  - {
      name: Domestic,
      type: select,
      proxies: [DIRECT, Proxy],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Domestic.png,
    }
  - {
      name: Private,
      type: select,
      proxies: [DIRECT, Proxy],
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lock.png,
    }

  # 地区分组
  - {
      name: HongKong,
      type: fallback,
      include-all-providers: true,
      filter: "(?i)港|hk",
      lazy: true,
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png,
    }
  - {
      name: TaiWan,
      type: fallback,
      include-all-providers: true,
      filter: "(?i)台|tw",
      lazy: true,
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png,
    }
  - {
      name: Japan,
      type: fallback,
      include-all-providers: true,
      filter: "(?i)日|jp",
      lazy: true,
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png,
    }
  - {
      name: Singapore,
      type: fallback,
      include-all-providers: true,
      filter: "(?i)(新加坡|sg)",
      lazy: true,
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png,
    }
  - {
      name: USA,
      type: fallback,
      include-all-providers: true,
      filter: "(?i)美|us",
      lazy: true,
      icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png,
    }

rule-providers:
  fakeip-filter:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/fakeip-filter.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/fakeip-filter.mrs"
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  Download:
    type: http
    behavior: classical
    path: ./rules/Download.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml"
    interval: 86400

  private:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/private.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/private.mrs"
    interval: 86400

  ads:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/ads.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/ads.mrs"
    interval: 86400

  microsoft-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/microsoft-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/microsoft-cn.mrs"
    interval: 86400

  apple-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/apple-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/apple-cn.mrs"
    interval: 86400

  google-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/google-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/google-cn.mrs"
    interval: 86400

  games-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/games-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/games-cn.mrs"
    interval: 86400

  ai:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/ai.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/ai.mrs"
    interval: 86400

  networktest:
    type: http
    behavior: classical
    format: text
    path: ./rules/networktest.list
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/networktest.list"
    interval: 86400

  proxy:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/proxy.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/proxy.mrs"
    interval: 86400

  cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/cn.mrs"
    interval: 86400

  telegramip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/telegramip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/telegramip.mrs"
    interval: 86400

  privateip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/privateip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/privateip.mrs"
    interval: 86400

  cnip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/cnip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/cnip.mrs"
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    path: ./rules/GoogleFCM.yaml
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
    interval: 86400

  Samsung:
    type: http
    behavior: classical
    path: ./rules/Samsung.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Samsung/Samsung.yaml"
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./rules/Streaming.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml"
    interval: 86400

rules:
  - RULE-SET,private,Private
  - RULE-SET,applications,DIRECT
  - RULE-SET,Download,DIRECT
  - RULE-SET,GoogleFCM,DIRECT
  - RULE-SET,networktest,DIRECT
  - RULE-SET,ads,REJECT
  - RULE-SET,apple-cn,Apple
  - RULE-SET,google-cn,Google
  - RULE-SET,microsoft-cn,Microsoft
  - RULE-SET,Samsung,Samsung
  - RULE-SET,ai,AI
  - RULE-SET,games-cn,Game
  - RULE-SET,Streaming,Streaming
  - RULE-SET,proxy,Global
  - RULE-SET,cn,Domestic
  - RULE-SET,telegramip,Telegram,no-resolve
  - RULE-SET,privateip,Private,no-resolve
  - RULE-SET,cnip,Domestic
  - MATCH,Final
