- path: output/ai.yaml
  behavior: domain
  upstream:
    dler_ai:
      type: http
      url: "https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/AI%20Suite.yaml"
    ACL4SSR_ai:
      type: http
      url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list"

- path: output/apple@cn.yaml
  behavior: domain
  upstream:
    skk_apple_services:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/apple_services.txt"
    skk_apple_cn:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt"
    skk_apple_cdn:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt"
    skk_apple_cdn_non_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/apple_cdn.txt"

- path: output/cdn.yaml
  behavior: domain
  upstream:
    skk_cdn_domainset:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/cdn.txt"
    skk_cdn_non_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/cdn.txt"

- path: output/cdn@ip.yaml
  behavior: ipcidr
  upstream:
    skk_cdn_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/cdn.txt"

- path: output/direct.yaml
  behavior: domain
  upstream:
    skk_direct:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/direct.txt"
    dler_scholar:
      type: http
      url: "https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Scholar.yaml"

- path: output/domestic.yaml
  behavior: domain
  upstream:
    skk_domestic:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/domestic.txt"
    dler_dom:
      type: http
      url: "https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Domestic.yaml"

- path: output/domestic@ip.yaml
  behavior: ipcidr
  upstream:
    skk_domestic_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/domestic.txt"
    skk_china_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/china_ip.txt"
    dler_dom_ip:
      type: http
      url: "https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Domestic%20IPs.yaml"

- path: output/download.yaml
  behavior: domain
  upstream:
    skk_download_domainset:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/download.txt"
    skk_download_non_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/download.txt"

- path: output/download@ip.yaml
  behavior: ipcidr
  upstream:
    skk_download_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/download.txt"

- path: output/private.yaml
  behavior: domain
  upstream:
    private:
      type: http
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"

- path: output/private@ip.yaml
  behavior: ipcidr
  upstream:
    privateip:
      type: http
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"

- path: output/proxy.yaml
  behavior: domain
  upstream:
    skk_global:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/global.txt"
    dler_proxy:
      type: http
      url: "https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Proxy.yaml"

- path: output/reject.yaml
  behavior: domain
  upstream:
    xndeye_reject:
      type: http
      url: "https://cdn.jsdelivr.net/gh/xndeye/adblock_list@beta/rule/clash.yaml"
    dler_ad:
      type: http
      url: "https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/AdBlock.yaml"

- path: output/reject@ip.yaml
  behavior: ipcidr
  upstream:
    skk_reject_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/reject.txt"
    dler_ad:
      type: http
      url: "https://cdn.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/AdBlock.yaml"

- path: output/stream.yaml
  behavior: domain
  upstream:
    skk_stream:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/stream.txt"

- path: output/stream@ip.yaml
  behavior: ipcidr
  upstream:
    skk_stream_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/stream.txt"

- path: output/telegram@ip.yaml
  behavior: ipcidr
  upstream:
    skk_telegram_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/telegram.txt"
