name: update rules

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次
  workflow_dispatch:        # 允许手动触发

permissions:
  actions: write    # 允许删除工作流运行
  contents: write   # 允许推送更改

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python rule_merger.py

      - name: Clean up
        run: |
          find . -maxdepth 1 ! -name 'output' ! -name '.' ! -name '.git' -exec rm -rf {} +
          mv output/* .
          rm -rf output

      - name: Get current time
        id: time
        run: |
          echo "TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🚀 Update at ${{ steps.time.outputs.TIME }}
          branch: release
          skip_dirty_check: true
          push_options: '--force'
          create_branch: true
          skip_fetch: true
          skip_checkout: true
          commit_options: '--allow-empty'

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1